default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: decision-maker_development

test:
  <<: *default
  database: decision-maker_test

production:
  <<: *default
  database: decision-maker_production
  username: decision-maker
  password: <%= ENV['DECISION-MAKER_DATABASE_PASSWORD'] %>
